### PR TITLE
pull

### PR DESCRIPTION
**Pull request by diasdavid**
@dignifiedquire can you try the examples/echo?

### CODE REVIEW

**Comment by dignifiedquire** [comment]
- Example is working
- Tests are working except one, but not sure where the failure is coming from:

```
libp2p-ipfs crash that node, make sure nodeA continues going steady:
     Uncaught AssertionError: expected [ Array(4) ] to have a length of 3 but got 4
      at Timeout.check [as _onTimeout] (test/libp2p.spec.js:413:42)
```

**Comment by diasdavid** [comment]
Seems that the cleanup is not done properly, because errors are not being propagate as they should.

**Comment by dignifiedquire** [comment]
> Seems that the cleanup is not done properly, because errors are not being propagate as they should.

I figured out why it's not closing, in the stream -> pull-stream -> stream conversion between tcp and spdy the `close` event gets lost, and only `end` is emitted to spdy, resulting in spdy not properly closing things. I have a hack to fix it, but need to investigate more to find a good fix.

**Comment by dignifiedquire** [comment]
@diasdavid fixed with this: https://github.com/libp2p/js-libp2p-spdy/pull/16/commits/be7f084a107499dfb4a6871bab86f46b9c3d8a36

**Pull request merged**
